# Generated by Django 5.2.17 on 2026-09-16 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='título')),
                ('url_imagen', models.URLField(help_text='Dirección web de la imagen, ej: https://picsum.photos/id/10/800/600', max_length=500, verbose_name='URL de la imagen')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('publicada', models.BooleanField(default=True)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'foto',
                'verbose_name_plural': 'fotos',
                'ordering': ['-creada'],
            },
        ),
    ]
